### ISSUE TITLE
Подготовить концепт

### ISSUE THREAD

**Issue by LuckyDenis** [LuckyDenis/italian-russian-dictionary#1]
Обсудить какой будет минимальный функционал у словаря для пользователя

**Comment by LuckyDenis** [comment]
Как храним
------------
- В памяти программы в словаре. Где ключами будут слова которые водит пользователь, а значение ключей список значений

Пользовательский интерфейс
--------------------------------
- Поиск по слову
- Цикличный (интерактивный) поиск
- Выход по команде
- Добавление новых значений
- Обновление старых значений
- Строится на базе цикла `while`

**Comment by Tamiris7** [comment]
что происходит выше?
