### ISSUE TITLE
Подготовить словарь

### ISSUE THREAD

**Issue by LuckyDenis** [LuckyDenis/italian-russian-dictionary#4]
- [x] Слздать файл main.py
- [x] Нужно подготовить хранилище данных согласно концеп-документу #1
- [x] Добавить туда 10 слов-ключей
- [x] Сделать pull request (PR)
- [x] Пройти review

**Comment by LuckyDenis** [comment]
Первичная оценка: 1 час

**Comment by Tamiris7** [comment]
#3 cделано

**Comment by Tamiris7** [comment]
виижу
